"""Inictial Schema Creation

Revision ID: 3c5c82d1105d
Revises: 
Create Date: 2026-04-13 17:51:31.168303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c5c82d1105d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'match_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('match', 'score_team_one',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('match', 'score_team_two',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('match', 'round_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('match', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player', 'email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('player', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('player', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('player', 'id_region',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('player_email_key'), 'player', type_='unique')
    op.alter_column('player_profile', 'total_matches',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_profile', 'total_wins',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_profile', 'total_losses',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_profile', 'total_points',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_profile', 'ranking_position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player_profile', 'last_update',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('player_profile', 'id_player',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player_team', 'join_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('team', 'creation_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('team', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('team', 'id_region',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_tournament', 'points_obtained',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_tournament', 'registered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tournament', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('tournament', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('tournament', 'prize_pool',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    op.alter_column('tournament', 'max_teams',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tournament', 'id_region',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tournament', 'id_video_game_type',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tournament', 'id_tournament_mode',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tournament', 'id_tournament_status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tournament_mode', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('tournament_status', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('video_game_type', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_game_type', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tournament_status', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tournament_mode', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tournament', 'id_tournament_status',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tournament', 'id_tournament_mode',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tournament', 'id_video_game_type',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tournament', 'id_region',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tournament', 'max_teams',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tournament', 'prize_pool',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('tournament', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('tournament', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('team_tournament', 'registered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('team_tournament', 'points_obtained',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team', 'id_region',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('team', 'creation_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('player_team', 'join_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('player_profile', 'id_player',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player_profile', 'last_update',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('player_profile', 'ranking_position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player_profile', 'total_points',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_profile', 'total_losses',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_profile', 'total_wins',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_profile', 'total_matches',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_unique_constraint(op.f('player_email_key'), 'player', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('player', 'id_region',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('player', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('player', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('match', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('match', 'round_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('match', 'score_team_two',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('match', 'score_team_one',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('match', 'match_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
