"""Added last_update attribute

Revision ID: 8d8f5cc8b213
Revises: 5bbeaf4479b3
Create Date: 2026-05-11 00:24:32.671592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d8f5cc8b213'
down_revision: Union[str, Sequence[str], None] = '5bbeaf4479b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
